# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/k3gxx/setup-makefiles.sh

PRODUCT_COPY_FILES += \
  vendor/samsung/k3gxx/proprietary/app/FFFFFFFF000000000000000000000001.drbin:$(TARGET_COPY_OUT_VENDOR)/app/FFFFFFFF000000000000000000000001.drbin \
  vendor/samsung/k3gxx/proprietary/app/mcRegistry/00060308060501020000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/00060308060501020000000000000000.tlbin \
  vendor/samsung/k3gxx/proprietary/app/mcRegistry/02010000080300030000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/02010000080300030000000000000000.tlbin \
  vendor/samsung/k3gxx/proprietary/app/mcRegistry/07010000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07010000000000000000000000000000.tlbin \
  vendor/samsung/k3gxx/proprietary/app/mcRegistry/07060000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07060000000000000000000000000000.tlbin \
  vendor/samsung/k3gxx/proprietary/app/mcRegistry/ffffffff000000000000000000000003.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff000000000000000000000003.tlbin \
  vendor/samsung/k3gxx/proprietary/app/mcRegistry/ffffffff000000000000000000000004.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff000000000000000000000004.tlbin \
  vendor/samsung/k3gxx/proprietary/app/mcRegistry/ffffffff000000000000000000000005.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff000000000000000000000005.tlbin \
  vendor/samsung/k3gxx/proprietary/app/mcRegistry/ffffffff000000000000000000000007.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff000000000000000000000007.tlbin \
  vendor/samsung/k3gxx/proprietary/app/mcRegistry/ffffffff000000000000000000000008.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff000000000000000000000008.tlbin \
  vendor/samsung/k3gxx/proprietary/app/mcRegistry/ffffffff000000000000000000000009.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff000000000000000000000009.tlbin \
  vendor/samsung/k3gxx/proprietary/app/mcRegistry/ffffffff00000000000000000000000a.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff00000000000000000000000a.tlbin \
  vendor/samsung/k3gxx/proprietary/app/mcRegistry/ffffffff00000000000000000000000c.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff00000000000000000000000c.tlbin \
  vendor/samsung/k3gxx/proprietary/app/mcRegistry/ffffffff00000000000000000000000d.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff00000000000000000000000d.tlbin \
  vendor/samsung/k3gxx/proprietary/app/mcRegistry/ffffffff00000000000000000000000e.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff00000000000000000000000e.tlbin \
  vendor/samsung/k3gxx/proprietary/app/mcRegistry/ffffffff00000000000000000000000f.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff00000000000000000000000f.tlbin \
  vendor/samsung/k3gxx/proprietary/app/mcRegistry/ffffffff000000000000000000000011.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff000000000000000000000011.tlbin \
  vendor/samsung/k3gxx/proprietary/app/mcRegistry/ffffffff000000000000000000000012.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff000000000000000000000012.tlbin \
  vendor/samsung/k3gxx/proprietary/app/mcRegistry/ffffffff000000000000000000000013.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff000000000000000000000013.tlbin \
  vendor/samsung/k3gxx/proprietary/app/mcRegistry/ffffffff000000000000000000000016.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff000000000000000000000016.tlbin \
  vendor/samsung/k3gxx/proprietary/app/mcRegistry/ffffffff000000000000000000000017.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff000000000000000000000017.tlbin \
  vendor/samsung/k3gxx/proprietary/app/mcRegistry/ffffffff000000000000000000000018.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff000000000000000000000018.tlbin \
  vendor/samsung/k3gxx/proprietary/app/mcRegistry/ffffffffd00000000000000000000004.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffffd00000000000000000000004.tlbin \
  vendor/samsung/k3gxx/proprietary/app/mcRegistry/ffffffffd0000000000000000000000a.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffffd0000000000000000000000a.tlbin \
  vendor/samsung/k3gxx/proprietary/app/mcRegistry/ffffffffd0000000000000000000000e.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffffd0000000000000000000000e.tlbin \
  vendor/samsung/k3gxx/proprietary/app/mcRegistry/ffffffffd00000000000000000000016.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffffd00000000000000000000016.tlbin \
  vendor/samsung/k3gxx/proprietary/bin/drmserver:$(TARGET_COPY_OUT_VENDOR)/bin/drmserver \
  vendor/samsung/k3gxx/proprietary/bin/gpsd:$(TARGET_COPY_OUT_VENDOR)/bin/hw/gpsd \
  vendor/samsung/k3gxx/proprietary/bin/scranton_RD:$(TARGET_COPY_OUT_VENDOR)/bin/scranton_RD \
  vendor/samsung/k3gxx/proprietary/bin/sensorhubservice:$(TARGET_COPY_OUT_VENDOR)/bin/sensorhubservice \
  vendor/samsung/k3gxx/proprietary/etc/wifi/bcmdhd_apsta.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/wifi/bcmdhd_apsta.bin \
  vendor/samsung/k3gxx/proprietary/etc/wifi/cred.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/wifi/cred.conf \
  vendor/samsung/k3gxx/proprietary/etc/wifi/nvram_net.txt:$(TARGET_COPY_OUT_SYSTEM)/etc/wifi/nvram_net.txt \
  vendor/samsung/k3gxx/proprietary/etc/wifi/bcmdhd_ibss.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/wifi/bcmdhd_ibss.bin \
  vendor/samsung/k3gxx/proprietary/etc/wifi/nvram_mfg.txt:$(TARGET_COPY_OUT_SYSTEM)/etc/wifi/nvram_mfg.txt \
  vendor/samsung/k3gxx/proprietary/etc/wifi/nvram_net.txt_semco3rd:$(TARGET_COPY_OUT_SYSTEM)/etc/wifi/nvram_net.txt_semco3rd \
  vendor/samsung/k3gxx/proprietary/etc/wifi/bcmdhd_mfg.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/wifi/bcmdhd_mfg.bin \
  vendor/samsung/k3gxx/proprietary/etc/wifi/nvram_mfg.txt_semco3rd:$(TARGET_COPY_OUT_SYSTEM)/etc/wifi/nvram_mfg.txt_semco3rd \
  vendor/samsung/k3gxx/proprietary/etc/wifi/nvram_net.txt_wisol:$(TARGET_COPY_OUT_SYSTEM)/etc/wifi/nvram_net.txt_wisol \
  vendor/samsung/k3gxx/proprietary/etc/wifi/bcmdhd_sta.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/wifi/bcmdhd_sta.bin \
  vendor/samsung/k3gxx/proprietary/etc/wifi/nvram_mfg.txt_wisol:$(TARGET_COPY_OUT_SYSTEM)/etc/wifi/nvram_mfg.txt_wisol \
  vendor/samsung/k3gxx/proprietary/lib/lib_SamsungRec_V04004.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib_SamsungRec_V04004.so \
  vendor/samsung/k3gxx/proprietary/lib/lib_Samsung_Resampler.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib_Samsung_Resampler.so \
  vendor/samsung/k3gxx/proprietary/lib/libaudio-ril.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudio-ril.so \
  vendor/samsung/k3gxx/proprietary/lib/libaudioroute.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libaudioroute.so \
  vendor/samsung/k3gxx/proprietary/lib/libsamsungSoundbooster_ext.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsamsungSoundbooster_ext.so \
  vendor/samsung/k3gxx/proprietary/lib/libcontrolcsc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcontrolcsc.so \
  vendor/samsung/k3gxx/proprietary/lib/libsecnativefeature.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsecnativefeature.so \
  vendor/samsung/k3gxx/proprietary/lib/lib_DNSe_NRSS_ver226.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib_DNSe_NRSS_ver226.so \
  vendor/samsung/k3gxx/proprietary/lib/libsec-ril.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsec-ril.so \
  vendor/samsung/k3gxx/proprietary/lib/libdrmdecrypt.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdrmdecrypt.so \
  vendor/samsung/k3gxx/proprietary/lib/libsensorhubservice.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsensorhubservice.so \
  vendor/samsung/k3gxx/proprietary/lib/libexynoscamera.so:$(TARGET_COPY_OUT_VENDOR)/lib/libexynoscamera.so \
  vendor/samsung/k3gxx/proprietary/lib/libsensorhub.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsensorhub.so \
  vendor/samsung/k3gxx/proprietary/lib/libgnustl_shared.so:$(TARGET_COPY_OUT_VENDOR)/lib/libgnustl_shared.so \
  vendor/samsung/k3gxx/proprietary/lib/lib_soundaliveresampler.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib_soundaliveresampler.so \
  vendor/samsung/k3gxx/proprietary/lib/libhdcp2.so:$(TARGET_COPY_OUT_VENDOR)/lib/libhdcp2.so \
  vendor/samsung/k3gxx/proprietary/lib/lib_SoundAlive_SRC192_ver205.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib_SoundAlive_SRC192_ver205.so \
  vendor/samsung/k3gxx/proprietary/lib/liboemcrypto.so:$(TARGET_COPY_OUT_VENDOR)/lib/liboemcrypto.so \
  vendor/samsung/k3gxx/proprietary/lib/lib_SoundBooster_ver504.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib_SoundBooster_ver504.so \
  vendor/samsung/k3gxx/proprietary/lib/libril.so:$(TARGET_COPY_OUT_VENDOR)/lib/libril.so \
  vendor/samsung/k3gxx/proprietary/lib/libstagefright_hdcp.so:$(TARGET_COPY_OUT_VENDOR)/lib/libstagefright_hdcp.so \
  vendor/samsung/k3gxx/proprietary/lib/lib_Samsung_AudioZoom_v102.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib_Samsung_AudioZoom_v102.so \
  vendor/samsung/k3gxx/proprietary/lib/libvdis.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvdis.so \
  vendor/samsung/k3gxx/proprietary/lib/libsamsungRecord_ns.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsamsungRecord_ns.so \
  vendor/samsung/k3gxx/proprietary/lib/libwrappergps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libwrappergps.so \
  vendor/samsung/k3gxx/proprietary/lib/libsamsungRecord.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsamsungRecord.so \
  vendor/samsung/k3gxx/proprietary/lib/libsamsungRecord_zoom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsamsungRecord_zoom.so \
  vendor/samsung/k3gxx/proprietary/lib/drm/libdrmwvmplugin.so:$(TARGET_COPY_OUT_VENDOR)/lib/drm/libdrmwvmplugin.so \
  vendor/samsung/k3gxx/proprietary/lib/hw/audio.primary.universal5422.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/audio.primary.universal5422.so \
  vendor/samsung/k3gxx/proprietary/lib/hw/power.exynos5.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/power.exynos5.so \
  vendor/samsung/k3gxx/proprietary/lib/hw/camera.universal5422.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/camera.universal5422.so \
  vendor/samsung/k3gxx/proprietary/lib/hw/sensorhubs.universal5422.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/sensorhubs.universal5422.so \
  vendor/samsung/k3gxx/proprietary/lib/hw/gps.default.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/gps.default.so \
  vendor/samsung/k3gxx/proprietary/lib/hw/sensors.universal5422.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/sensors.universal5422.so \
  vendor/samsung/k3gxx/proprietary/lib/hw/nfc_nci.universal5422.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/nfc_nci.universal5422.so \
  vendor/samsung/k3gxx/proprietary/lib/omx/libOMX.Exynos.AVC.Decoder.so:$(TARGET_COPY_OUT_VENDOR)/lib/omx/libOMX.Exynos.AVC.Decoder.so \
  vendor/samsung/k3gxx/proprietary/lib/omx/libOMX.Exynos.VP8.Decoder.so:$(TARGET_COPY_OUT_VENDOR)/lib/omx/libOMX.Exynos.VP8.Decoder.so \
  vendor/samsung/k3gxx/proprietary/lib/omx/libOMX.Exynos.AVC.Encoder.so:$(TARGET_COPY_OUT_VENDOR)/lib/omx/libOMX.Exynos.AVC.Encoder.so \
  vendor/samsung/k3gxx/proprietary/lib/omx/libOMX.Exynos.VP8.Encoder.so:$(TARGET_COPY_OUT_VENDOR)/lib/omx/libOMX.Exynos.VP8.Encoder.so \
  vendor/samsung/k3gxx/proprietary/lib/omx/libOMX.Exynos.MPEG4.Decoder.so:$(TARGET_COPY_OUT_VENDOR)/lib/omx/libOMX.Exynos.MPEG4.Decoder.so \
  vendor/samsung/k3gxx/proprietary/lib/omx/libOMX.Exynos.WMV.Decoder.so:$(TARGET_COPY_OUT_VENDOR)/lib/omx/libOMX.Exynos.WMV.Decoder.so \
  vendor/samsung/k3gxx/proprietary/lib/omx/libOMX.Exynos.MPEG4.Encoder.so:$(TARGET_COPY_OUT_VENDOR)/lib/omx/libOMX.Exynos.MPEG4.Encoder.so \
  vendor/samsung/k3gxx/proprietary/usr/idc/Synaptics_HID_TouchPad.idc:$(TARGET_COPY_OUT_SYSTEM)/usr/idc/Synaptics_HID_TouchPad.idc \
  vendor/samsung/k3gxx/proprietary/usr/share/alsa/alsa.conf:$(TARGET_COPY_OUT_SYSTEM)/usr/share/alsa/alsa.conf \
  vendor/samsung/k3gxx/proprietary/vendor/firmware/bcm4350_V0301.0562.hcd:$(TARGET_COPY_OUT_VENDOR)/firmware/bcm4350_V0301.0562.hcd \
  vendor/samsung/k3gxx/proprietary/vendor/firmware/bcm4350_V0301.0563_wisol.hcd:$(TARGET_COPY_OUT_VENDOR)/firmware/bcm4350_V0301.0563_wisol.hcd \
  vendor/samsung/k3gxx/proprietary/vendor/firmware/companion_2p2_master_setfile.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/companion_2p2_master_setfile.bin \
  vendor/samsung/k3gxx/proprietary/vendor/firmware/companion_2p2_mode_setfile.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/companion_2p2_mode_setfile.bin \
  vendor/samsung/k3gxx/proprietary/vendor/firmware/companion_default_coef.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/companion_default_coef.bin \
  vendor/samsung/k3gxx/proprietary/vendor/firmware/companion_default_lsc.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/companion_default_lsc.bin \
  vendor/samsung/k3gxx/proprietary/vendor/firmware/companion_fw_2p2_evt1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/companion_fw_2p2_evt1.bin \
  vendor/samsung/k3gxx/proprietary/vendor/firmware/companion_fw_evt0.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/companion_fw_evt0.bin \
  vendor/samsung/k3gxx/proprietary/vendor/firmware/fimc_is_fw2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/fimc_is_fw2.bin \
  vendor/samsung/k3gxx/proprietary/vendor/firmware/fimc_is_fw2_2p2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/fimc_is_fw2_2p2.bin \
  vendor/samsung/k3gxx/proprietary/vendor/firmware/libpn547_fw.so:$(TARGET_COPY_OUT_VENDOR)/firmware/libpn547_fw.so \
  vendor/samsung/k3gxx/proprietary/vendor/firmware/mfc_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mfc_fw.bin \
  vendor/samsung/k3gxx/proprietary/vendor/firmware/setfile_2p2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/setfile_2p2.bin \
  vendor/samsung/k3gxx/proprietary/vendor/firmware/setfile_6b2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/setfile_6b2.bin \
  vendor/samsung/k3gxx/proprietary/vendor/firmware/setfile_8b1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/setfile_8b1.bin \
  vendor/samsung/k3gxx/proprietary/vendor/lib/egl/libGLES_mali.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libGLES_mali.so \
  vendor/samsung/k3gxx/proprietary/vendor/lib/mediadrm/libdrmclearkeyplugin.so:$(TARGET_COPY_OUT_VENDOR)/lib/mediadrm/libdrmclearkeyplugin.so \
  vendor/samsung/k3gxx/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:$(TARGET_COPY_OUT_VENDOR)/lib/mediadrm/libwvdrmengine.so \
  vendor/samsung/k3gxx/proprietary/vendor/lib/liblvverx_3.21.13.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblvverx_3.21.13.so \
  vendor/samsung/k3gxx/proprietary/vendor/lib/liblvvetx_3.21.13.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblvvetx_3.21.13.so \
  vendor/samsung/k3gxx/proprietary/vendor/lib/libmalicore.bc:$(TARGET_COPY_OUT_VENDOR)/lib/libmalicore.bc \
  vendor/samsung/k3gxx/proprietary/vendor/lib/libOpenCL.so:$(TARGET_COPY_OUT_VENDOR)/lib/libOpenCL.so \
  vendor/samsung/k3gxx/proprietary/vendor/lib/libOpenCL.so.1:$(TARGET_COPY_OUT_VENDOR)/lib/libOpenCL.so.1 \
  vendor/samsung/k3gxx/proprietary/vendor/lib/libOpenCL.so.1.1:$(TARGET_COPY_OUT_VENDOR)/lib/libOpenCL.so.1.1 \
  vendor/samsung/k3gxx/proprietary/vendor/lib/libRSDriverArm.so:$(TARGET_COPY_OUT_VENDOR)/lib/libRSDriverArm.so \
  vendor/samsung/k3gxx/proprietary/vendor/lib/libwvdrm_L1.so:$(TARGET_COPY_OUT_VENDOR)/lib/libwvdrm_L1.so \
  vendor/samsung/k3gxx/proprietary/vendor/lib/libwvm.so:$(TARGET_COPY_OUT_VENDOR)/lib/libwvm.so \
  vendor/samsung/k3gxx/proprietary/vendor/lib/libWVStreamControlAPI_L1.so:$(TARGET_COPY_OUT_VENDOR)/lib/libWVStreamControlAPI_L1.so \
  vendor/samsung/k3gxx/proprietary/vendor/media/LMspeed_508.emd:$(TARGET_COPY_OUT_VENDOR)/media/LMspeed_508.emd \
  vendor/samsung/k3gxx/proprietary/vendor/media/PFFprec_600.emd:$(TARGET_COPY_OUT_VENDOR)/media/PFFprec_600.emd
